rwth-acis/RequirementsBazaar

- src/main/de/rwth/dbis/acis/bazaar/service/CategoryResource.java
- src/main/de/rwth/dbis/acis/bazaar/service/ProjectsResource.java
- src/main/de/rwth/dbis/acis/bazaar/service/dal/repositories/CategoryRepositoryImpl.java
- src/main/de/rwth/dbis/acis/bazaar/service/dal/repositories/ProjectRepositoryImpl.java
- src/main/de/rwth/dbis/acis/bazaar/service/dal/repositories/RequirementRepositoryImpl.java
- src/main/de/rwth/dbis/acis/bazaar/service/dal/transform/CategoryTransformer.java
- src/main/de/rwth/dbis/acis/bazaar/service/dal/transform/ProjectTransformer.java
- src/main/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
> Last activity sort

- .github/workflows/release_rc.yaml
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/BazaarService.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/CategoryResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Attachment.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/EntityContext.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/EntityOverview.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Statistic.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/PaginationResult.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/exception/ExceptionHandler.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/NotificationDispatcherImp.java
Resolves #79 and incorrect datetime serialization.
> Fix Datetime bug

- CHANGELOG.md
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/AttachmentsResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/CategoryResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/CommentsResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/PersonalisationDataResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/ProjectsResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/RequirementsResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/UsersResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/Pageable.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/CategoryTransformer.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/ProjectTransformer.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
Closes #82 
Allows natural sorting for attribute names.
> Separate sort direction attribute 

- CHANGELOG.md
- docs/Privileges.md
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacade.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeImpl.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Comment.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/EntityBase.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/PrivilegeEnum.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/User.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/PaginationResult.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/SerializerViews.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/UserRepository.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/UserRepositoryImpl.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/UserTransformer.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/ProjectsResource.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/UsersResource.java
- requirement_bazaar/src/main/resources/migrations/V8__new_privileges.sql
- requirement_bazaar/src/test/java/de/rwth/dbis/acis/bazaar/service/BazaarTest.java
Introduces a search endpoint for users.
This also introduces JSONViews to decide which attributes of a user should be returned.
> User search

- CHANGELOG.md
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeImpl.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Category.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Project.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Requirement.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CategoryRepositoryImpl.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/ProjectRepositoryImpl.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/RequirementRepositoryImpl.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/ActivityDispatcher.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/EmailDispatcher.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/NotificationDispatcherImp.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- requirement_bazaar/src/main/resources/migrations/V9__more_delete_constraints.sql
- requirement_bazaar/src/test/java/de/rwth/dbis/acis/bazaar/service/BazaarTest.java
Closes #81 by adding the lastActivity attribute.
While optimizing and removing duplicated code categories have been removed from the requirements object and replaced by a list of category ids.
> Last activity

- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/BazaarService.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/RequirementRepositoryImpl.java
- requirement_bazaar/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- requirement_bazaar/src/test/java/de/rwth/dbis/acis/bazaar/service/BazaarTest.java
Fix bug in rc.4 beta with requirements not being displayed correctly and add according testcase.
> Fix get requirements by category

- CHANGELOG.md
- docs/Privileges.md
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacade.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Attachment.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Category.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Comment.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Ownable.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/PrivilegeEnum.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Project.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Requirement.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CategoryRepository.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CategoryRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/CommentsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/ProjectsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- reqbaz/src/main/resources/migrations/V10__delete_project.sql
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/BazaarTest.java
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeTest.java
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/helpers/SetupData.java
> Category Bugfix and API Consistency

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/CategoryTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/ProjectTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
- reqbaz/src/main/resources/migrations/V11__natural_sort_function.sql
> Fix natural sorting by magic sql function

- reqbaz/build.gradle
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/BazaarService.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacade.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Comment.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/PageInfo.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CommentRepository.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CommentRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/RoleRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/UserRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/VoteRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/CategoryTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/CommentTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/ProjectTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/UserTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/VoteTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/CommentsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/ProjectsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- reqbaz/src/main/resources/i18n/Translation_de.properties
- reqbaz/src/main/resources/i18n/Translation_en.properties
- reqbaz/src/main/resources/migrations/V11__natural_sort_function.sql
- reqbaz/src/main/resources/migrations/V12__comment_delete.sql
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeTest.java
Allow comments to be soft-deleted.
Closes #101 
Requires #102 to be merged.
> Comment softdelete

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CommentRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/CommentsResource.java
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/BazaarTest.java
Something prevented the put to be mapped correctly.
Users are no longer returned in redacted comments.
> Comment update fix

- CHANGELOG.md
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Category.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Project.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Requirement.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/CategoryTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/ProjectTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
- reqbaz/src/main/resources/migrations/V14__entity_json_properties.sql
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/BazaarTest.java
An additional json type field for each of these entities to allow storing addiotnal data, such as linked github repositories or associated issues.
> Additional properties for projects, categories and requirements

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/PageInfo.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/Pageable.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/ProjectRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/ProjectsResource.java
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/BazaarTest.java
Allows to include requirements into the search scope of projects.
> Allow project search to recurse through linked entities

- CHANGELOG.md
- docker-compose.yml
- gradle.properties
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
This fixes a permission issue on the requirement realize endpoint encountered during cae integration tests.
> Realize Permission Hotfix

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/ProjectTransformer.java
Workaround: ts_vector based search only works on full words that also need to be recognized by an internal english dictionary. This simple addition enables simple substring based autocomplete search while keeping the ts_vector based search for project descriptions.
> Simple name substring match for project search

- etc/de.rwth.dbis.acis.bazaar.service.BazaarService.properties
- gradle.properties
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/WebhookResource.java
Original changes from [florisa:ba-zanier](https://github.com/florisa/RequirementsBazaar/tree/ba-zanier) merged into this feature branch for testing with latest develop version. See original pull request for some comments: https://github.com/rwth-acis/RequirementsBazaar/pull/113
> Feature: GitHub Webhook

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/BazaarService.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacade.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Activity.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/UserStatistics.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/UserRepository.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/UserRepositoryImpl.java
> feat: new resource for user statistics

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/BazaarService.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/AdminResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/twitter/TweetDispatcher.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/twitter/WeeklyNewProjectsTweetTask.java
- Weekly Tweet (on Sunday afternoon, 4 pm) about new projects in Requirements Bazaar
- If only one new project, the new project is linked directly
- If multiple new projects, two are named in the Tweet and a link to the list of new projects is posted
> Feature: Weekly new projects tweet

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Activity.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/EmailDispatcher.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/NotificationDispatcherImp.java
> Fix: email notification links + emails never sent

- CHANGELOG.md
- gradle.properties
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Activity.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/EmailDispatcher.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/notification/NotificationDispatcherImp.java
- Fixed wrong requirement link in email notifications
[#151](https://github.com/rwth-acis/RequirementsBazaar/pull/151)
> Release: v0.12.1

- gradle.properties
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/RequirementRepositoryImpl.java
> Fix: Requirement pagination

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
Fixed:
- https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/issues/147
- https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/issues/236 (duplicate)
> Fix: Allow creator of requirement to delete it

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Requirement.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/EntityContextFactory.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CommentRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/RequirementRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- reqbaz/src/main/resources/changelog.yaml
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/helpers/SetupData.java
Resolves:
* https://github.com/rwth-acis/RequirementsBazaar/issues/163
* includes a database migration
> feat: add lastUpdatingUser property to requirements

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Requirement.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/RequirementRepositoryImpl.java
Adds information about the user who performed the latest activity on a requirement.
Implements
- https://github.com/rwth-acis/RequirementsBazaar/issues/161
> Feature: last activity user

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/CategoryResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/CommentsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/FeedbackResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/ProjectsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/security/AuthorizationManager.java
Fixes first part of #166 (members could not develop requirement)
> Fix: member cannot develop requirement

- CHANGELOG.md
- etc/i5.las2peer.webConnector.WebConnector.properties
- gradle.properties
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/DALFacadeImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Requirement.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/helpers/EntityContextFactory.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/CommentRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/repositories/RequirementRepositoryImpl.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/transform/RequirementTransformer.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/CategoryResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/CommentsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/FeedbackResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/ProjectsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/security/AuthorizationManager.java
- reqbaz/src/main/resources/changelog.yaml
- reqbaz/src/test/java/de/rwth/dbis/acis/bazaar/service/helpers/SetupData.java
- Add information about the user who last updated a requirement to API responses (in the `lastUpdatingUser` property)
[#164](https://github.com/rwth-acis/RequirementsBazaar/pull/164)
- Add information about the user who performed the last activity on a requirement to API responses (in the `lastActivityUser` property).
Editing, commenting, and adding attachments are examples for activities.
[#165](https://github.com/rwth-acis/RequirementsBazaar/pull/165)
- Fixed authorization error which caused members of a project not being able to start (or stop) developing a requirement
[#167](https://github.com/rwth-acis/RequirementsBazaar/pull/167)
- Migrate to new OIDC domain (auth.las2peer.org)
[#168](https://github.com/rwth-acis/RequirementsBazaar/pull/168)
> Release 0.13.0

- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/dal/entities/Activity.java
- reqbaz/src/main/java/de/rwth/dbis/acis/bazaar/service/resources/RequirementsResource.java
- reqbaz/src/main/resources/i18n/Translation_en.properties
Implement API for moving requirements to other categories
> feat: add API for moving requirement to other project and category
